'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Swords,Shield,Trophy,Volume2,VolumeX,Pause,Play,ChevronRight,UserRound,LogOut,Skull,ArrowUp,ArrowDown,ArrowLeft,ArrowRight,Maximize,RotateCcw,Flame,ScrollText} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {KnightGame,type Hud,type Run} from '@/lib/game/engine';
import {scoreFor} from '@/lib/game/rules';
type User={id:string,username:string};type Entry={user_id:string,username:string,score:number,wave:number,rank:number};
const initialHud:Hud={hp:100,stamina:100,score:0,wave:1,kills:0,time:0,banner:''};
async function api(path:string,body?:unknown){const response=await fetch('/api'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json','X-Knight-Request':'1'},body:body===undefined?undefined:JSON.stringify(body)});let data;try{data=await response.json()}catch{throw Error('The server is unavailable. Please try again.')}if(!response.ok)throw Error(data.error||'Something went wrong.');return data;}
const number=(v:number)=>Number(v).toLocaleString('en-US');const clock=(v:number)=>`${Math.floor(v/60).toString().padStart(2,'0')}:${Math.floor(v%60).toString().padStart(2,'0')}`;
export default function Home(){
 const [user,setUser]=useState<User|null>(null),[authLoading,setAuthLoading]=useState(true),[view,setView]=useState('arena'),[authOpen,setAuthOpen]=useState(false),[authMode,setAuthMode]=useState('register'),[authError,setAuthError]=useState(''),[busy,setBusy]=useState(false);
 const [mode,setMode]=useState<'ready'|'playing'|'over'>('ready'),[paused,setPaused]=useState(false),[muted,setMuted]=useState(false),[hud,setHud]=useState<Hud>(initialHud),[run,setRun]=useState<Run|null>(null),[saveStatus,setSaveStatus]=useState(''),[startError,setStartError]=useState('');
 const [entries,setEntries]=useState<Entry[]>([]),[rank,setRank]=useState<Entry|null>(null),[leaderError,setLeaderError]=useState(''),[leaderLoading,setLeaderLoading]=useState(true),[profile,setProfile]=useState<any>(null),[profileError,setProfileError]=useState(''),[guideOpen,setGuideOpen]=useState(false);
 const canvas=useRef<HTMLCanvasElement>(null),engine=useRef<KnightGame|null>(null),gameId=useRef<string|null>(null),stage=useRef<HTMLDivElement>(null),isPaused=useRef(false),currentUser=useRef<User|null>(null),finished=useRef<Run|null>(null),pendingSave=useRef(false);
 currentUser.current=user;
 const loadLeaders=useCallback(async()=>{setLeaderLoading(true);setLeaderError('');try{const d=await api('/leaderboard');setEntries(d.entries);setRank(d.me)}catch(e){setLeaderError((e as Error).message)}finally{setLeaderLoading(false)}},[]);
 const loadProfile=useCallback(async()=>{setProfileError('');try{setProfile(await api('/profile'))}catch(e){setProfileError((e as Error).message)}},[]);
 useEffect(()=>{api('/me').then(d=>setUser(d.user)).catch(()=>{}).finally(()=>setAuthLoading(false));void loadLeaders();return()=>engine.current?.destroy()},[loadLeaders]);
 useEffect(()=>{if(view==='profile'&&user)void loadProfile()},[view,user,loadProfile]);
 const togglePause=useCallback(()=>{if(!engine.current||engine.current.ended)return;isPaused.current=!isPaused.current;engine.current.setPause(isPaused.current);setPaused(isPaused.current)},[]);
 async function saveResult(result:Run){if(!gameId.current||!currentUser.current){setSaveStatus('Guest run · create an account before your next run to save it.');return}if(pendingSave.current)return;pendingSave.current=true;setSaveStatus('Saving your run…');try{await api('/games/finish',{gameId:gameId.current,...result});setSaveStatus('Run saved to your chronicle.');void loadLeaders();setProfile(null)}catch(e){setSaveStatus((e as Error).message)}finally{pendingSave.current=false}}
 async function start(){if(busy)return;setBusy(true);setStartError('');try{gameId.current=user?(await api('/games/start',{})).id:null;engine.current?.destroy();setHud(initialHud);setRun(null);finished.current=null;setSaveStatus('');setPaused(false);isPaused.current=false;setMode('playing');setView('arena');
  // The canvas is always mounted; initialization remains in the user gesture for audio.
  const g=new KnightGame(canvas.current!,setHud,(result)=>{finished.current=result;setRun(result);setMode('over');void saveResult(result)},togglePause);g.muted=muted;g.unlockAudio();engine.current=g;canvas.current?.focus();
 }catch(e){setStartError((e as Error).message)}finally{setBusy(false)}}
 function changeView(value:string){if(mode==='playing'&&!isPaused.current){isPaused.current=true;engine.current?.setPause(true);setPaused(true)}setView(value);if(value==='leaderboard')void loadLeaders()}
 function openAuth(mode='register'){if(engine.current&&!engine.current.ended&&!isPaused.current)togglePause();setAuthMode(mode);setAuthError('');setAuthOpen(true)}
 async function submitAuth(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setAuthError('');const data=Object.fromEntries(new FormData(e.currentTarget));try{const d=await api('/auth/'+authMode,data);setUser(d.user);setAuthOpen(false);void loadLeaders()}catch(e){setAuthError((e as Error).message)}finally{setBusy(false)}}
 async function logout(){try{await api('/auth/logout',{});setUser(null);setProfile(null);setRank(null);setView('arena')}catch(e){setStartError((e as Error).message)}}
 function touch(code:string,down:boolean){if(down){engine.current?.keys.add(code);engine.current?.unlockAudio()}else engine.current?.keys.delete(code)}
 const best=entries.find(e=>e.user_id===user?.id)?.score??rank?.score??0;
 return <div className="app-shell">
  <header className="topbar"><a href="/" className="brand" aria-label="The Last Knight home"><span className="brand-mark"><Swords size={24}/></span><span>THE LAST KNIGHT<small>A PIXEL CHRONICLE</small></span></a><nav aria-label="Account"><button className="text-button guide-link" onClick={()=>{if(engine.current&&!engine.current.ended&&!isPaused.current)togglePause();setGuideOpen(true)}}>How to play</button>{authLoading?<span className="subtle">Loading…</span>:user?<><button className="account" onClick={()=>changeView('profile')}><UserRound size={16}/>{user.username}</button><button className="icon-button" onClick={logout} disabled={mode==='playing'} aria-label="Sign out"><LogOut size={17}/></button></>:<><button className="text-button" onClick={()=>openAuth('login')}>Sign in</button><button className="outline-button" onClick={()=>openAuth()}>Create account <ChevronRight size={15}/></button></>}</nav></header>
  <main><div className="page-heading"><div><div className="eyebrow"><span/> THE KINGDOM STILL NEEDS YOU</div><h1>One knight. One last stand.</h1></div><span className="chapter">CHAPTER I <i/> THE FALLEN KEEP</span></div>
  <Tabs value={view} onValueChange={changeView} className="main-tabs"><div className="tabbar"><TabsList className="game-tabs" variant="line"><TabsTrigger value="arena"><Swords/>The arena</TabsTrigger><TabsTrigger value="leaderboard"><Trophy/>Hall of legends</TabsTrigger><TabsTrigger value="profile"><ScrollText/>My chronicle</TabsTrigger></TabsList><span className="season-label">SURVIVAL / ENDLESS WAVES</span></div>
  <TabsContent value="arena" forceMount hidden={view!=='arena'} className="arena-layout"><section className="game-column">
   <div className="game-frame" ref={stage}><div className="game-topline"><span><span className="mini-dot"/>THE FALLEN KEEP</span><div><button className="icon-button" aria-label={muted?'Unmute sound':'Mute sound'} onClick={()=>{setMuted(!muted);if(engine.current)engine.current.muted=!muted}}>{muted?<VolumeX size={16}/>:<Volume2 size={16}/>}</button><button className="icon-button" onClick={togglePause} disabled={mode!=='playing'} aria-label={paused?'Resume':'Pause'}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><button className="icon-button fullscreen" aria-label="Fullscreen" onClick={()=>{if(!document.fullscreenElement)void stage.current?.requestFullscreen().catch(()=>{});else void document.exitFullscreen()}}><Maximize size={15}/></button></div></div>
   <div className="arena"><canvas ref={canvas} tabIndex={0} aria-label="Knight survival arena. WASD to move, Space to attack, E to block, Shift to dodge." className={mode==='ready'?'canvas-idle':''}/>
    {mode==='ready'&&<div className="start-screen"><img src="/art/castle.png" alt="A lone knight watches over a ruined, torchlit castle courtyard"/><div className="start-shade"/><div className="start-content"><div className="ornament">✦ <span>STEEL ENDURES. LEGENDS REMAIN.</span> ✦</div><h2><span>THE LAST</span>KNIGHT</h2><p>The kingdom has fallen.<br/>Your sword has not.</p><button className="gold-button play-button" onClick={start} disabled={busy||authLoading}><Swords size={20}/>{busy?'Entering the keep…':'Enter the arena'}<ChevronRight size={18}/></button><span className="start-note">{user?`Playing as ${user.username}`:'Play instantly · no account needed'}</span></div><span className="art-caption">THE FALLEN KEEP · DUSK</span></div>}
    {mode==='playing'&&<><div className="hud"><div className="hud-vitals"><label><span>VITALITY</span><b>{Math.ceil(hud.hp)} / 100</b></label><Progress value={hud.hp} className="health" aria-label="Health"/><Progress value={hud.stamina} className="stamina" aria-label="Stamina"/></div><div className="hud-wave"><small>WAVE</small><strong>{String(hud.wave).padStart(2,'0')}</strong></div><div className="hud-score"><small>SCORE</small><strong>{number(hud.score).padStart(5,'0')}</strong></div></div>{hud.banner&&!paused&&<div className="wave-banner">{hud.banner}</div>}<div className="run-clock">{clock(hud.time)}</div></>}
    {paused&&mode==='playing'&&<div className="game-overlay"><div className="overlay-card"><Shield size={32}/><div className="eyebrow">TAKE A BREATH</div><h2>The battle can wait.</h2><p>Your run is paused.</p><button className="gold-button" onClick={togglePause}><Play size={17}/>Resume battle</button></div></div>}
    {mode==='over'&&run&&<div className="game-overlay"><div className="overlay-card gameover"><Skull size={28}/><div className="eyebrow">A VALIANT LAST STAND</div><h2>Rest, brave knight.</h2><div className="final-score">{number(scoreFor(run.kills,run.wave-1))}<small>POINTS EARNED</small></div><p>Wave {run.wave} <span>·</span> {Object.values(run.kills).reduce((a,b)=>a+b,0)} enemies slain <span>·</span> {clock(run.duration)}</p><span className="save-status" role="status">{saveStatus}</span>{gameId.current&&saveStatus&&!saveStatus.startsWith('Run saved')&&!saveStatus.startsWith('Saving')&&<button className="text-button" onClick={()=>saveResult(run)}>Retry saving</button>}<button className="gold-button" onClick={start} disabled={busy||pendingSave.current}><RotateCcw size={17}/>{busy?'Preparing…':'Rise again'}</button></div></div>}
   </div><div className="game-bottomline"><span><Shield size={14}/> {user?user.username:'Wandering knight'}</span><span>{mode==='ready'?'YOUR LEGEND STARTS HERE':`${hud.kills} SLAIN`}<i/>{mode==='playing'?'HOLD THE KEEP':'ENDLESS MODE'}</span></div></div>
   {startError&&<p className="error" role="alert">{startError}</p>}
   <div className="touch-controls" aria-label="Touch game controls"><div className="dpad">{[['ArrowUp',ArrowUp],['ArrowLeft',ArrowLeft],['ArrowDown',ArrowDown],['ArrowRight',ArrowRight]].map(([code,Icon]:any)=><button key={code} aria-label={code.replace('Arrow','Move ')} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);touch(code,true)}} onPointerUp={()=>touch(code,false)} onPointerCancel={()=>touch(code,false)}><Icon size={18}/></button>)}</div><div className="touch-actions">{[['Space','Attack'],['KeyE','Block'],['ShiftLeft','Dodge']].map(([code,label])=><button key={code} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);touch(code,true)}} onPointerUp={()=>touch(code,false)} onPointerCancel={()=>touch(code,false)}>{label}</button>)}</div></div>
   <div className="controls-strip"><div><span className="key-cluster"><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd></span><span>Move</span></div><div><kbd className="wide-key">SPACE</kbd><span>Attack</span></div><div><kbd>E</kbd><span>Shield</span></div><div><kbd className="wide-key">SHIFT</kbd><span>Dodge</span></div><div><kbd>ESC</kbd><span>Pause</span></div></div>
   <div className="tip"><Flame size={16}/><p><strong>A word of wisdom</strong> Face your enemy before you strike. Save your stamina for the moments that matter.</p></div>
  </section><aside className="sidebar"><section className="side-panel knight-panel"><div className="panel-label">YOUR JOURNEY <Shield size={15}/></div><div className="knight-identity"><div className="avatar"><Swords size={29}/></div><div><h3>{user?user.username:'Wandering knight'}</h3><span>{user?'Keeper of the fallen realm':'Every legend starts somewhere'}</span></div></div><div className="personal-stats"><div><span>PERSONAL BEST</span><strong>{user?number(best):'—'}</strong></div><div><span>RANK</span><strong>{rank?'#'+rank.rank:'—'}</strong></div></div>{!user&&<><p>Give your knight a name.<br/>Keep your place in history.</p><button className="outline-button full-width" onClick={()=>openAuth()}>Save your legend<ChevronRight size={15}/></button></>}</section>
  <section className="side-panel legends-panel"><div className="panel-label">HALL OF LEGENDS <Trophy size={15}/></div><p className="side-subtitle">The keep remembers its bravest.</p>{leaderLoading?<p className="empty-copy">Loading legends…</p>:leaderError?<div className="empty-copy">{leaderError}<button className="text-button" onClick={loadLeaders}>Try again</button></div>:entries.length?<ol className="mini-leaders">{entries.slice(0,4).map((e,i)=><li key={e.user_id}><span className={'rank-badge rank-'+i}>{String(i+1).padStart(2,'0')}</span><span>{e.username}<small>Wave {e.wave}</small></span><strong>{number(e.score)}</strong></li>)}</ol>:<div className="empty-leaders"><Trophy size={26}/><strong>An unwritten history</strong><p>Finish a ranked run to become<br/>the keep’s first legend.</p></div>}<button className="text-button leaderboard-link" onClick={()=>changeView('leaderboard')}>View all legends <ChevronRight size={15}/></button></section>
  <section className="lore-panel"><span>THE OATH</span><p>“Though the banners fall,<br/>I shall not.”</p><small>— THE LAST KNIGHT</small></section></aside></TabsContent>
  <TabsContent value="leaderboard"><section className="large-panel"><div className="section-heading"><div><div className="eyebrow">THE KEEP REMEMBERS</div><h2>Hall of legends</h2><p>One best run per knight. A hundred places in history.</p></div><Trophy size={36}/></div>{rank&&<div className="rank-callout">Your place: <strong>#{rank.rank}</strong> · {number(rank.score)} points · wave {rank.wave}</div>}{leaderLoading?<p>Loading legends…</p>:leaderError?<p className="error">{leaderError} <button onClick={loadLeaders}>Retry</button></p>:entries.length?<Table><TableHeader><TableRow><TableHead>Rank</TableHead><TableHead>Knight</TableHead><TableHead>Wave</TableHead><TableHead className="text-right">Score</TableHead></TableRow></TableHeader><TableBody>{entries.map(e=><TableRow key={e.user_id} className={e.user_id===user?.id?'your-row':''}><TableCell className="gold">#{e.rank}</TableCell><TableCell>{e.username}{e.user_id===user?.id&&<small className="you-label">YOU</small>}</TableCell><TableCell>{e.wave}</TableCell><TableCell className="text-right score-cell">{number(e.score)}</TableCell></TableRow>)}</TableBody></Table>:<div className="big-empty"><Trophy size={38}/><h3>The first legend could be you.</h3><p>Create an account and finish a run to claim your place.</p><button className="gold-button" onClick={()=>user?changeView('arena'):openAuth()}>{user?'Enter the arena':'Create your knight'}</button></div>}</section></TabsContent>
  <TabsContent value="profile"><section className="large-panel"><div className="section-heading"><div><div className="eyebrow">YOUR STORY, SO FAR</div><h2>My chronicle</h2><p>{user?`The deeds of ${user.username}.`:'A name is the beginning of a legend.'}</p></div><ScrollText size={36}/></div>{!user?<div className="big-empty"><Shield size={38}/><h3>Make your mark.</h3><p>Create an account to save scores and revisit your battles.</p><button className="gold-button" onClick={()=>openAuth()}>Create your knight</button><button className="text-button" onClick={()=>openAuth('login')}>Already a knight? Sign in</button></div>:profileError?<p className="error">{profileError}<button onClick={loadProfile}>Retry</button></p>:!profile?<p>Opening your chronicle…</p>:<><div className="profile-stats">{[['BEST SCORE',number(profile.stats.best)],['BATTLES FOUGHT',number(profile.stats.games)],['ENEMIES SLAIN',number(profile.stats.kills)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><h3 className="history-title">Recent battles</h3>{profile.history.length?<Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Wave</TableHead><TableHead>Slain</TableHead><TableHead>Time</TableHead><TableHead className="text-right">Score</TableHead></TableRow></TableHeader><TableBody>{profile.history.map((r:any,i:number)=><TableRow key={i}><TableCell>{new Date(r.created_at*1000).toLocaleDateString()}</TableCell><TableCell>{r.wave}</TableCell><TableCell>{r.kills}</TableCell><TableCell>{clock(r.duration)}</TableCell><TableCell className="text-right score-cell">{number(r.score)}</TableCell></TableRow>)}</TableBody></Table>:<p className="empty-copy">No battles yet. The keep is waiting.</p>}</>}</section></TabsContent></Tabs>
  </main><footer><span><Swords size={13}/> THE LAST KNIGHT</span><p>Steel in your hand. History in the making.</p><span>EST. MMXXVI</span></footer>
  <Dialog open={authOpen} onOpenChange={setAuthOpen}><DialogContent className="knight-dialog"><div className="modal-emblem"><Shield size={29}/></div><DialogTitle>{authMode==='register'?'Every knight needs a name.':'Welcome back, knight.'}</DialogTitle><DialogDescription>{authMode==='register'?'Create your account to save runs and join the hall of legends.':'Sign in and continue your chronicle.'}</DialogDescription><form onSubmit={submitAuth} className="auth-form">{authMode==='register'&&<label>Knight name<input autoComplete="username" name="username" placeholder="e.g. AshenKnight" required minLength={3} maxLength={20} pattern="[a-zA-Z0-9_]+"/></label>}<label>Email<input name="email" type="email" autoComplete="email" placeholder="you@example.com" required/></label><label>Password<input name="password" type="password" autoComplete={authMode==='register'?'new-password':'current-password'} placeholder="At least 8 characters" minLength={8} maxLength={128} required/></label>{authError&&<p className="error" role="alert">{authError}</p>}<button className="gold-button full-width" type="submit" disabled={busy}>{busy?'One moment…':authMode==='register'?'Create your knight':'Sign in'}<ChevronRight size={16}/></button></form><button className="text-button" onClick={()=>{setAuthMode(authMode==='register'?'login':'register');setAuthError('')}}>{authMode==='register'?'Already have an account? Sign in':'New to the keep? Create an account'}</button></DialogContent></Dialog>
  <Dialog open={guideOpen} onOpenChange={v=>{if(v&&engine.current&&!isPaused.current)togglePause();setGuideOpen(v)}}><DialogContent className="knight-dialog"><DialogTitle>Hold the fallen keep.</DialogTitle><DialogDescription>Survive waves of enemies. Every fifth wave brings the Warden.</DialogDescription><div className="guide-list"><p><kbd>WASD</kbd> or arrow keys to move and face enemies.</p><p><kbd>SPACE</kbd> strikes in front of you. Click the arena to aim and strike.</p><p><kbd>E</kbd> blocks attacks from the direction you face.</p><p><kbd>SHIFT</kbd> dodges. Blocking and dodging use stamina.</p><p><kbd>ESC</kbd> or P pauses. Switching tabs also pauses the battle.</p><p>Collect green potions for +25 HP. Clearing a wave restores 8 HP.</p><p>Skeleton: 10 pts · Goblin: 20 · Dark knight: 50 · Warden: 250. Cleared wave: +100.</p><p>Sign in <strong>before starting</strong> to save your score. Guest runs are practice.</p></div></DialogContent></Dialog>
 </div>
}
