import {WIDTH,HEIGHT,emptyCounts,scoreFor,waveEnemies,type Counts,type Kind} from './rules';
export type Hud={hp:number,stamina:number,score:number,wave:number,kills:number,time:number,banner:string};
export type Run={kills:Counts,wave:number,duration:number};
type Enemy={x:number,y:number,kind:Kind,hp:number,max:number,speed:number,cd:number,flash:number};
type Particle={x:number,y:number,vx:number,vy:number,life:number,color:string};
const knight=['......hhhh......','.....hAAAAh.....','.....hABBAh.....','.....hAAAAh.....','......DDDD......','...rrLAAAAL.....','..rrrLACCAL.....','..rrrLAAAAL.....','...rrLAAAAL.....','....r.GGGG......','......A..A......','......A..A......','.....HH..HH.....'];
const goblin=['....G......G....','....GGGGGGGG....','.....GgGGgG.....','.....GxGGxG.....','......GGGG......','.....BLLLLB.....','....GBLLLLBG....','....GBLLLLBG....','......LLLL......','......G..G......','.....BB..BB.....'];
const skeleton=['......AAAA......','.....AAAAAA.....','.....AxAAxA.....','......AAAA......','.......AA.......','....AA.AA.AA....','.....AAAAAA.....','....AA.AA.AA....','.......AA.......','......A..A......','......A..A......','.....AA..AA.....'];
const palettes:any={player:{h:'#536375',A:'#d3d6cc',B:'#17232f',D:'#b7a386',L:'#8b9cac',C:'#52687e',r:'#a4403c',G:'#56514d',H:'#333b49'},goblin:{G:'#7c9960',g:'#a3ba7f',x:'#ffbf69',L:'#674d3e',B:'#302c35'},skeleton:{A:'#c3bea7',x:'#3c3945'},knight:{h:'#282634',A:'#727a85',B:'#eea352',D:'#45344b',L:'#49536a',C:'#292d40',r:'#46325c',G:'#282534',H:'#1e2030'},boss:{h:'#342538',A:'#887e94',B:'#ff7949',D:'#3b293f',L:'#594260',C:'#e79d60',r:'#672e46',G:'#312339',H:'#282333'}};
export class KnightGame{
 canvas:HTMLCanvasElement;ctx:CanvasRenderingContext2D;keys=new Set<string>();x=480;y=290;angle=Math.PI/2;hp=100;stamina=100;wave=1;kills=emptyCounts();elapsed=0;enemies:Enemy[]=[];particles:Particle[]=[];drops:{x:number,y:number}[]=[];queue:Kind[]=[];spawn=0;between=0;attack=0;attackCd=0;dash=0;dashCd=0;invincible=0;paused=false;ended=false;muted=false;shield=false;frame=0;last=0;hudAt=0;audio:AudioContext|null=null;banner='WAVE 01';bannerTime=2;shake=0;onHud:(hud:Hud)=>void;onEnd:(run:Run)=>void;onPause:()=>void;
 constructor(canvas:HTMLCanvasElement,onHud:(h:Hud)=>void,onEnd:(r:Run)=>void,onPause:()=>void){this.canvas=canvas;this.ctx=canvas.getContext('2d')!;this.ctx.imageSmoothingEnabled=false;this.onHud=onHud;this.onEnd=onEnd;this.onPause=onPause;this.queue=waveEnemies(1);canvas.width=WIDTH;canvas.height=HEIGHT;window.addEventListener('keydown',this.keyDown);window.addEventListener('keyup',this.keyUp);window.addEventListener('blur',this.blur);document.addEventListener('visibilitychange',this.visibility);canvas.addEventListener('pointerdown',this.pointer);this.frame=requestAnimationFrame(this.loop);this.sendHud();}
 keyDown=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches('input,textarea'))return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','KeyE','ShiftLeft','ShiftRight','Escape','KeyP'].includes(e.code)){e.preventDefault();if((e.code==='Escape'||e.code==='KeyP')&&!e.repeat){this.onPause();return}this.keys.add(e.code)}};
 keyUp=(e:KeyboardEvent)=>{this.keys.delete(e.code)};
 blur=()=>{this.keys.clear();if(!this.paused&&!this.ended)this.onPause()};
 visibility=()=>{if(document.hidden)this.blur()};
 pointer=(e:PointerEvent)=>{if(this.paused||this.ended)return;const r=this.canvas.getBoundingClientRect();this.angle=Math.atan2((e.clientY-r.top)/r.height*HEIGHT-this.y,(e.clientX-r.left)/r.width*WIDTH-this.x);this.swing();this.canvas.focus()};
 setPause(value:boolean){this.paused=value;this.keys.clear()}
 unlockAudio(){try{this.audio??=new AudioContext();void this.audio.resume()}catch{}}
 sound(freq:number,duration=.07,type:OscillatorType='square',volume=.025){if(this.muted||!this.audio)return;const a=this.audio,o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.setValueAtTime(freq,a.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(40,freq*.5),a.currentTime+duration);g.gain.setValueAtTime(volume,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+duration);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+duration)}
 emit(x:number,y:number,color:string,count=8){for(let i=0;i<count;i++)this.particles.push({x,y,vx:(Math.random()-.5)*160,vy:(Math.random()-.5)*160,life:.3+Math.random()*.25,color})}
 swing(){if(this.attackCd>0||this.paused||this.ended)return;this.attack=.18;this.attackCd=.34;this.sound(240,.09,'sawtooth',.02);
  for(const e of this.enemies){const dx=e.x-this.x,dy=e.y-this.y,dist=Math.hypot(dx,dy);const angleDiff=Math.atan2(Math.sin(Math.atan2(dy,dx)-this.angle),Math.cos(Math.atan2(dy,dx)-this.angle));if(dist<(e.kind==='boss'?103:77)&&Math.abs(angleDiff)<1.15){e.hp-=e.kind==='boss'?27:34;e.flash=.12;e.x+=dx/(dist||1)*12;e.y+=dy/(dist||1)*12;this.emit(e.x,e.y,'#d5b176',5);this.shake=3;if(e.hp<=0){this.kills[e.kind]++;if(Math.random()<.13)this.drops.push({x:e.x,y:e.y});this.emit(e.x,e.y,e.kind==='goblin'?'#839260':'#9294a4',12)}}}
  this.enemies=this.enemies.filter(e=>e.hp>0);
 }
 addEnemy(kind:Kind){const side=Math.floor(Math.random()*4);const boss=kind==='boss';const hp=boss?240+this.wave*12:kind==='knight'?100:kind==='goblin'?45:34;this.enemies.push({kind,x:side<2?(side===0?40:920):80+Math.random()*800,y:side>=2?(side===2?55:490):80+Math.random()*380,hp,max:hp,speed:(kind==='goblin'?66:kind==='skeleton'?42:boss?32:36)+Math.min(25,this.wave*1.2),cd:1,flash:0})}
 update(dt:number){this.elapsed+=dt;this.attack=Math.max(0,this.attack-dt);this.attackCd-=dt;this.dashCd-=dt;this.invincible-=dt;this.dash-=dt;this.bannerTime-=dt;this.shake*=.8;
  let dx=(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0),dy=(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0)-(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0);const len=Math.hypot(dx,dy);if(len){dx/=len;dy/=len;this.angle=Math.atan2(dy,dx)}
  this.shield=this.keys.has('KeyE')&&this.stamina>1&&this.dash<=0;
  if((this.keys.has('ShiftLeft')||this.keys.has('ShiftRight'))&&this.dashCd<=0&&this.stamina>=30){this.dash=.16;this.dashCd=.75;this.invincible=.2;this.stamina-=30;this.sound(380,.06,'triangle')}
  const speed=this.dash>0?490:this.shield?85:170;
  this.x=Math.max(42,Math.min(WIDTH-42,this.x+(this.dash>0?Math.cos(this.angle):dx)*speed*dt));this.y=Math.max(64,Math.min(HEIGHT-40,this.y+(this.dash>0?Math.sin(this.angle):dy)*speed*dt));
  this.stamina=Math.max(0,Math.min(100,this.stamina+(this.shield?-17:23)*dt));if(this.keys.has('Space'))this.swing();
  this.spawn-=dt;if(this.queue.length&&this.spawn<=0){this.addEnemy(this.queue.shift()!);this.spawn=.65}
  if(!this.queue.length&&!this.enemies.length){if(this.between===0){this.between=2.5;this.banner='WAVE CLEARED';this.bannerTime=2;this.sound(550,.18,'triangle');}this.between-=dt;if(this.between<=0){this.wave++;this.between=0;this.queue=waveEnemies(this.wave);this.banner='WAVE '+String(this.wave).padStart(2,'0')+(this.wave%5===0?' · THE WARDEN':'');this.bannerTime=2.5;this.hp=Math.min(100,this.hp+8)}}
  for(const e of this.enemies){e.flash-=dt;e.cd-=dt;const ex=this.x-e.x,ey=this.y-e.y,dist=Math.hypot(ex,ey);if(dist>25){e.x+=ex/dist*e.speed*dt;e.y+=ey/dist*e.speed*dt}if(dist<(e.kind==='boss'?42:29)&&e.cd<=0&&this.invincible<=0){e.cd=.9;const diff=Math.abs(Math.atan2(Math.sin(Math.atan2(e.y-this.y,e.x-this.x)-this.angle),Math.cos(Math.atan2(e.y-this.y,e.x-this.x)-this.angle)));if(this.shield&&diff<1.4){this.stamina=Math.max(0,this.stamina-12);this.sound(700,.04,'triangle');this.emit(this.x,this.y,'#90bac6',4)}else{this.hp=Math.max(0,this.hp-(e.kind==='boss'?25:e.kind==='knight'?18:10));this.invincible=.65;this.shake=8;this.sound(85,.15,'sawtooth',.04);this.emit(this.x,this.y,'#a85a55',10)}}}
  // Soft separation keeps enemies readable instead of stacking into a single sprite.
  for(let i=0;i<this.enemies.length;i++)for(let j=i+1;j<this.enemies.length;j++){const a=this.enemies[i],b=this.enemies[j],dx=a.x-b.x,dy=a.y-b.y,d=Math.hypot(dx,dy);if(d>0&&d<23){const push=(23-d)*.5;a.x+=dx/d*push;a.y+=dy/d*push;b.x-=dx/d*push;b.y-=dy/d*push}}
  this.drops=this.drops.filter(d=>{if(Math.hypot(this.x-d.x,this.y-d.y)<27){this.hp=Math.min(100,this.hp+25);this.sound(650,.1,'sine');this.emit(d.x,d.y,'#7cbea0');return false}return true});
  this.particles=this.particles.filter(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;return p.life>0});
  if(this.hp<=0){this.ended=true;this.sendHud();this.onEnd({kills:{...this.kills},wave:this.wave,duration:this.elapsed})}
 }
 sprite(x:number,y:number,kind:string,scale=2,flash=false,moving=false){const c=this.ctx;const pattern=kind==='goblin'?goblin:kind==='skeleton'?skeleton:knight;const p=palettes[kind];c.fillStyle='#080e1580';c.beginPath();c.ellipse(x,y+12*scale,10*scale,4*scale,0,0,Math.PI*2);c.fill();const bob=moving?Math.round(Math.sin(this.elapsed*12)*1.5):0;pattern.forEach((row,yy)=>[...row].forEach((v,xx)=>{if(v==='.')return;c.fillStyle=flash?'#fff4d2':p[v]||'#929ba5';const step=yy>9&&moving?(xx<8?Math.sin(this.elapsed*12):Math.cos(this.elapsed*12))*2:0;c.fillRect(Math.round(x+(xx-8)*scale),Math.round(y+(yy-6)*scale+bob+step),scale,scale)}));
  if(kind==='player'||kind==='knight'||kind==='boss'){c.save();c.translate(x,y+4);c.rotate(kind==='player'?this.angle:Math.PI/2);c.fillStyle='#dfdcd0';c.fillRect(18,-2,22,4);c.fillStyle='#ad8952';c.fillRect(15,-6,4,12);c.fillStyle='#554433';c.fillRect(10,-2,7,4);c.restore()}
 }
 draw(){const c=this.ctx;c.save();c.fillStyle='#151e29';c.fillRect(0,0,WIDTH,HEIGHT);if(this.shake>1)c.translate((Math.random()-.5)*this.shake,(Math.random()-.5)*this.shake);
  for(let y=0;y<HEIGHT;y+=32)for(let x=0;x<WIDTH;x+=48){const n=((x*17+y*7)%37);c.fillStyle=n<12?'#202b36':n<24?'#222e39':'#26313b';c.fillRect(x+1+(y%64?24:0),y+1,46,30);c.fillStyle='#2a364080';c.fillRect(x+3+(y%64?24:0),y+2,41,2);if(n<8){c.fillStyle='#151f2b';c.fillRect(x+18,y+13,9,2);c.fillRect(x+26,y+15,2,6)}}
  // Arena boundaries and collision space are part of the playable map.
  c.strokeStyle='#55606a';c.lineWidth=2;c.strokeRect(32,48,896,464);c.strokeStyle='#36434d';c.strokeRect(39,55,882,450);c.fillStyle='#101824';c.fillRect(0,0,960,32);for(let x=0;x<960;x+=48){c.fillStyle='#3b4650';c.fillRect(x+2,3,44,22);c.fillStyle='#56606a';c.fillRect(x+2,3,44,3)}
  for(const x of [74,286,674,886]){const g=c.createRadialGradient(x,46,2,x,46,85);g.addColorStop(0,'#d18a352f');g.addColorStop(1,'#d18a3500');c.fillStyle=g;c.fillRect(x-85,0,170,135);c.fillStyle='#725340';c.fillRect(x-3,30,6,22);c.fillStyle='#da8344';c.fillRect(x-5,27,10,12);c.fillStyle='#ffe0a0';c.fillRect(x-2,22+Math.sin(this.elapsed*9+x)*3,4,13)}
  c.strokeStyle='#44505b';c.lineWidth=2;c.beginPath();c.arc(480,280,87,0,Math.PI*2);c.stroke();c.beginPath();c.arc(480,280,94,0,Math.PI*2);c.stroke();c.fillStyle='#37434f';c.fillRect(477,215,6,130);c.fillRect(427,250,106,6);
  for(const d of this.drops){c.fillStyle='#43675d';c.fillRect(d.x-6,d.y-6,12,14);c.fillStyle='#9ee0b0';c.fillRect(d.x-2,d.y-4,4,10);c.fillRect(d.x-5,d.y-1,10,4)}
  const actors=[...this.enemies.map(e=>({y:e.y,enemy:e})),{y:this.y,enemy:null}].sort((a,b)=>a.y-b.y);
  for(const a of actors){if(a.enemy){const e=a.enemy;this.sprite(e.x,e.y,e.kind,e.kind==='boss'?3:2,e.flash>0,true);if(e.hp<e.max){c.fillStyle='#10151d';c.fillRect(e.x-19,e.y-25,38,4);c.fillStyle=e.kind==='boss'?'#b487c1':'#b87565';c.fillRect(e.x-19,e.y-25,38*e.hp/e.max,4)}}else{c.globalAlpha=this.invincible>0&&Math.floor(this.elapsed*20)%2?0.5:1;this.sprite(this.x,this.y,'player',2,false,this.keys.size>0);c.globalAlpha=1;}}
  if(this.shield){c.save();c.translate(this.x,this.y);c.rotate(this.angle);c.fillStyle='#718f9f';c.fillRect(20,-16,6,32);c.fillStyle='#bad0d1';c.fillRect(23,-12,3,24);c.restore()}
  if(this.attack>0){c.strokeStyle='#ffdf9a';c.lineWidth=5;c.beginPath();c.arc(this.x,this.y,58,this.angle-1.05,this.angle+1.05);c.stroke();c.strokeStyle='#d5b47650';c.lineWidth=13;c.stroke()}
  for(const p of this.particles){c.fillStyle=p.color;c.globalAlpha=Math.min(1,p.life*3);c.fillRect(p.x,p.y,4,4)}c.globalAlpha=1;
  const vignette=c.createRadialGradient(480,270,170,480,270,540);vignette.addColorStop(0,'#060e1700');vignette.addColorStop(1,'#060e17aa');c.fillStyle=vignette;c.fillRect(0,0,960,540);c.restore();
 }
 sendHud(){this.onHud({hp:this.hp,stamina:this.stamina,score:scoreFor(this.kills,this.wave-1),wave:this.wave,kills:Object.values(this.kills).reduce((a,b)=>a+b,0),time:this.elapsed,banner:this.bannerTime>0?this.banner:''})}
 loop=(now:number)=>{const dt=Math.min(.033,(now-(this.last||now))/1000);this.last=now;if(!this.paused&&!this.ended)this.update(dt);this.draw();if(now-this.hudAt>100){this.hudAt=now;this.sendHud()}this.frame=requestAnimationFrame(this.loop)};
 destroy(){cancelAnimationFrame(this.frame);window.removeEventListener('keydown',this.keyDown);window.removeEventListener('keyup',this.keyUp);window.removeEventListener('blur',this.blur);document.removeEventListener('visibilitychange',this.visibility);this.canvas.removeEventListener('pointerdown',this.pointer);void this.audio?.close()}
}
